on:
  push:
    branches:
      - sdx
  workflow_dispatch:

name: Canary Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Run echo
        run: |
          echo "Teste ok"

  canaryDeploy:
    name: Canary Deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: AWS create new version
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "Teste ok"
  
  manual-approval:
    needs: canaryDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Aprovação Manual
        run: echo "Aprovar este job manualmente"
      - name: Aprovar
        run: echo "Job aprovado!"
        
  ManualApprove:
    needs: canaryDeploy
    runs-on: ubuntu-latest
    steps:
      - name: manual approve
        run: |
            echo "Manually approved"
  
  FinalyDeploy:
    name: FinalyDeploy
    needs: ManualApprove
    runs-on: ubuntu-latest
    
    steps:
      - name: AWS update weight 100% new version
        run: aws s3 ls
